version: '3.2'

services:

  message-queue:
    image: nats:windowsservercore
    networks:
      - app-net

  signup-app:
    image: dtrapp-dockeree-jjpo.uksouth.cloudapp.azure.com/ozcan/ddnet/mta-dev-signup-app:v4 
    depends_on:
      - message-queue
      - signup-homepage
    networks:
      - app-net

  signup-save-handler:
    image: dtrapp-dockeree-jjpo.uksouth.cloudapp.azure.com/ozcan/ddnet/mta-dev-signup-save-handler:v1
    depends_on:
      - message-queue
    networks:
      - app-net

  signup-index-handler:
    image: dtrapp-dockeree-jjpo.uksouth.cloudapp.azure.com/ozcan/ddnet/mta-dev-signup-index-handler:v1
    depends_on:
      - message-queue
      - elasticsearch
    networks:
      - app-net

  elasticsearch:
    image: dtrapp-dockeree-jjpo.uksouth.cloudapp.azure.com/ozcan/ddnet/elasticsearch:5.6.0-nanoserver
    networks:
      - app-net

  kibana:
    image: dtrapp-dockeree-jjpo.uksouth.cloudapp.azure.com/ozcan/ddnet/kibana:5.6.0-windowsservercore
    depends_on:
      - elasticsearch
    networks:
      - app-net

  signup-homepage:
    image: dtrapp-dockeree-jjpo.uksouth.cloudapp.azure.com/ozcan/ddnet/mta-dev-signup-homepage:v1
    networks:
      - app-net
