version: '3.2'

services:

  message-queue:
    image: nats:nanoserver
    networks:
      - app-net

  signup-app:
    image: dockersamples/mta-dev-signup-app:v4
    depends_on:
      - message-queue
      - signup-homepage
    networks:
      - app-net

  signup-save-handler:
    image: dockersamples/mta-dev-signup-save-handler:v1
    depends_on:
      - message-queue
    networks:
      - app-net

  signup-index-handler:
    image: dockersamples/mta-dev-signup-index-handler:v1
    depends_on:
      - message-queue
      - elasticsearch
    networks:
      - app-net

  elasticsearch:
    image: dockersamples/elasticsearch:5.6.0-nanoserver
    networks:
      - app-net

  kibana:
    image: dockersamples/kibana:5.6.0-windowsservercore
    depends_on:
      - elasticsearch
    networks:
      - app-net

  signup-homepage:
    image: dockersamples/mta-dev-signup-homepage:v1
    networks:
      - app-net